---
title: 'Reproduciblty Report: R MarkDown for  Real Data Analysis,Example:German Political Data'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading the R Package
```{r include=TRUE}
library(RBVNF)
load_packages()
load_additional_packages()

######
Effect_of_var<-function(beta_EM, sel_var ){

  baseLine_dir=beta_EM[1,]/ norm(beta_EM[1,])
  beta_sel_dir<-beta_EM[sel_var, ]/norm(beta_EM[sel_var, ])


  val_return<-as.numeric(acos(t(baseLine_dir)%*%beta_sel_dir))
  return(val_return)
}
```

# Loading the data and Data Summary

```{r }
#############################
  ##### Example 1
  #########################

Start_time= Sys.time()
  library(foreign) # for read.dta() funciton
  #library(Cairo)
  germany <- read.dta("data/RealData/germandata.dta")
  #attach(germany)
  summary(germany)
  # convert counterclockwise angles
  germany$direction.rad <- (360-germany$direction) / 360 * 2* pi
  #germany$direction.rad <- as.circular(germany$direction.rad, units = "radians",

```


# Preparing Data to run the Regression model for Directional Data:
```{r }

  #Constructing Response and Design Matrix
  Y= cbind(cos(germany$direction.rad), sin(germany$direction.rad))
  X_numerical= cbind(unemp=germany$unemp,
                     outofwed=germany$outofwed,
                     year=germany$year,
                     yearSQ=(germany$year)^2/100)

  X_categorical=cbind( Intercept=replicate(n = length(germany$direction.rad),1 ),
                      CduCsu=germany$cducsu,
                      Spd=germany$spd,
                      Green=germany$green,
                      Pds=germany$pds,
                      Reunification=germany$reunification)
  X_numerical =scale(X_numerical, scale = FALSE)
X=cbind(X_categorical, X_numerical)
```


# The Regresion for the directional data:
```{r }
SetMcLength=2000;
SetMcLength=max(SetMcLength, 2000)
  n=dim(Y)[1] # NUmber of the samples
  p=dim(X)[2] # NUmber of the regression covariates
  d=dim(Y)[2] # Number of direcions in the direcional data
  #### bbeta is a matrix of dimension p\times d
  #bbeta=matrix( rnorm(p*d), nrow=p, ncol=d)
  sigma_square=1
  tau_square=1000
```

# Running the Optimization Algorithm to obtain Posterior Mode:
```{r }
  beta_EM=EM_Dir_regression_optimizer_V1(Y=Y, X=X, prior=NULL, beta_init = NULL,   EM_tolerence = .00001)
print("Estimated Posterior Mode:=")
colnames(beta_EM)=gsub("Y_", "Beta_Y_",  colnames(beta_EM))
print(beta_EM)
```
  
  
  
  
  
# Running the Data Augmentation- MCMC Algorithm to obtain Posterior Mode:
```{r }
  lst_germany=MCMC_Dir_regression_sampler_V1(Y=Y, X=X, prior=NULL, beta_init = NULL,  MCSamplerSize =SetMcLength)
  #save(lst_germany, file="/data/Output_Workspaces/Germany_RUN_Example1_100.rdata")
```



# Plotting and Related Output:

```{r }
lst=lst_germany
  i=1;j= 1
  Plot_MCMC_Diag_Triplet(lst$MC$Mc_Beta[,i,j],y_lab_text = bquote(beta[.(i)][.(j)]))
  Beta_est=apply(lst$MC$Mc_Beta, MARGIN = c(2,3), FUN = mean)
  Beta_sd=apply(lst$MC$Mc_Beta, MARGIN = c(2,3), FUN = sd)
  Beta_est1<- matrix(paste0(  round(c(Beta_est),2),"(", round(c(Beta_sd),2),")& "), nrow=10)
  Beta_est2= cbind(paste(colnames(X),"&"), Beta_est1, paste("\\\\"))
  paste0(Beta_est2, collapse="//")
  cat(Beta_est2)
  #write.csv(Beta_est2, "/data/Output_Workspaces/Germany_RUN_Example1_regCoef.csv")
 # Effect_of_var(lst$MC$Mc_Beta[1, , ],4)
```



```{r }
norm<-function(x){sqrt(sum(x^2))}
  Beta_est_CI_L=apply(lst$MC$Mc_Beta, MARGIN = c(2,3), FUN = function(x){quantile(x, .025)})
  Beta_est_CI_R=apply(lst$MC$Mc_Beta, MARGIN = c(2,3), FUN = function(x){quantile(x, 1-.025)})
  CI_beta<- matrix(paste0("[",round(Beta_est_CI_L, 2)," , ", round(Beta_est_CI_R,2), "]"), ncol=10)



  ## CduCsu :Row= 2
  SPD_post<-apply(lst$MC$Mc_Beta, MARGIN = c(1), function(x){Effect_of_var(x,2)})
  p_1<-Plot_MCMC_Diag_Triplet(SPD_post,y_lab_text ="CduCsu")

  ## SPD :Row= 3
  SPD_post<-apply(lst$MC$Mc_Beta, MARGIN = c(1), function(x){Effect_of_var(x,3)})
  p_2<-Plot_MCMC_Diag_Triplet(SPD_post,y_lab_text ="SPD")
  ## Green :Row= 4
  Green_post<-apply(lst$MC$Mc_Beta, MARGIN = c(1), function(x){Effect_of_var(x,4)})
  p_3<-Plot_MCMC_Diag_Triplet(Green_post,y_lab_text ="Difference between `Green' and `FDP'")

  ## Green :Row= 5
  Psd_post<-apply(lst$MC$Mc_Beta, MARGIN = c(1), function(x){Effect_of_var(x,5)})
  p4<-Plot_MCMC_Diag_Triplet(Green_post,y_lab_text ="PSD")

  ###
  library(cowplot)

 # pdf(file="/data/Output_Workspaces/fig/Plot_Ger_PartyEfffects_TripletPlot.pdf", width = 10, height= 10)
  plot_grid(p_1, p_2,p_3,p4, ncol = 2)
 # dev.off()

 # pdf(file="/data/Output_Workspaces/fig/Plot_Ger_GREEN_TripletPlot.pdf", width = 6, height= 5)
  #plot_grid(p_1, p_2,p_3,p4, ncol = 2)
  p_3
 # dev.off()



  lst=lst_germany

  i=1;j= 1
  library(cowplot)
  i=1
  for(i in 1:9){
    i=10
#             pdf(file=paste0("//data/Output_Workspaces/fig/Plot_Ger_TripletPlot_Beta_",(i-1),".pdf"), width = 10, height= 5)
              #plot_grid(p_1, p_2,p_3,p4, ncol = 2)
             j=1; p1<-Plot_MCMC_Diag_Triplet(lst$MC$Mc_Beta[,i,1],y_lab_text = bquote(beta[.(i)][.(j)]))
             j=2; p2<-Plot_MCMC_Diag_Triplet(lst$MC$Mc_Beta[,i,2],y_lab_text = bquote(beta[.(i)][.(j)]))
              print(plot_grid(p1, p2, ncol = 2))
              #Sys.sleep(5)
 #             dev.off()
  }









  ## unemp :Row= 7
  unemp_post<-apply(lst$MC$Mc_Beta, MARGIN = c(1), function(x){Effect_of_var(x,7)})
  Plot_MCMC_Diag_Triplet(unemp_post,y_lab_text ="Effect of Unemployment Rate")

  ## Year :Row= 9
  year_post<-apply(lst$MC$Mc_Beta, MARGIN = c(1), function(x){Effect_of_var(x,9)})
  Plot_MCMC_Diag_Triplet(year_post,y_lab_text ="Year")

  Beta_est/Beta_sd


 End_time= Sys.time()
  print(paste0("Total Run Time=",End_time- Start_time , "minutes"))


```
